spring:
  application:
    name: APIGATEWAY
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "https://nookly-frontend-hslj.vercel.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: account-service
          uri: ${ACCOUNT_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/auth/**,/api/v1/owner/**,/api/v1/user/**,/api/v1/admin/**

        - id: add-pg-service
          uri: ${ADD_PG_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/pg-listings/**

        - id: pg-details-service
          uri: ${PG_DETAILS_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/pg/**,/addPGWithFiles,/my-pgs,/search

        - id: inquiry-service
          uri: ${INQUIRY_SERVICE_URL:https://nooklyinquiry.onrender.com}
          predicates:
            - Path=/inquiry/**

server:
  port: ${PORT:8080}

# No Eureka needed
eureka:
  client:
    enabled: false