spring:
  application:
    name: APIGATEWAY

  codec:
    max-in-memory-size: 200MB

  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 120s

      routes:
        - id: account-service
          uri: ${ACCOUNT_SERVICE_URL:https://nookaccount.onrender.com/}
          predicates:
            - Path=/api/v1/auth/**,/api/v1/owner/**,/api/v1/user/**,/api/v1/admin/**

        - id: add-pg-service
          uri: ${ADD_PG_SERVICE_URL:https://nookaddpg.onrender.com/}
          predicates:
            - Path=/api/pg-listings/**

        - id: pg-details-service
          uri: ${PG_DETAILS_SERVICE_URL:https://nookpgdetails.onrender.com/}
          predicates:
            - Path=/pg/**,/addPGWithFiles,/my-pgs,/search

        - id: inquiry-service
          uri: ${INQUIRY_SERVICE_URL:https://nooklyinquiry.onrender.com/}
          predicates:
            - Path=/inquiry/**

server:
  port: ${PORT:8080}

eureka:
  client:
    enabled: false