spring:
  application:
    name: APIGATEWAY
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "https://nookly-frontend-hslj.vercel.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        # ACCOUNT SERVICE
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/v1/auth/**,/api/v1/owner/**,/api/v1/user/**,/api/v1/admin/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

        # ADD PG SERVICE
        - id: add-pg-service
          uri: lb://ADD-PG-SERVICE
          predicates:
            - Path=/api/pg-listings/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

        # PG DETAILS SERVICE
        - id: pg-details-service
          uri: lb://PG-DETAILS-SERVICE
          predicates:
            - Path=/pg/**,/addPGWithFiles,/my-pgs,/search
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

        # INQUIRY SERVICE
        - id: inquiry-service
          uri: lb://INQUIRY-SERVICE
          predicates:
            - Path=/inquiry/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

server:
  port: ${PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:https://nookeureka-server.onrender.com/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${RENDER_EXTERNAL_HOSTNAME:apigateway-x0ku.onrender.com}
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info